### ISSUE TITLE
PandocRuby converts < and > in block codes to &lt; and &gt;

### ISSUE THREAD

**Issue by jmuheim** [alphabetum/pandoc-ruby#14]
PandocRuby:

    [5] irb »  PandocRuby.convert "Inline Code: `<asdf>`\n\n    Block code! <asdf>"
    => "<p>Inline Code: <code>&lt;asdf&gt;</code></p>\n<pre><code>Block code! &lt;asdf&gt;</code></pre>\n"

Pandoc:

    $ pandoc
    Inline Code: `<asdf>`

        Block code! <asdf>
    --- Ctrl-D ---
    <p>Inline Code: <code>&lt;asdf&gt;</code></p>
    <pre><code>Block code! &lt;asdf&gt;</code></pre>

**Comment by jmuheim** [comment]
With a file `code-test.md` like this:

```
Inline Code: `<asdf>`

    Block code! <asdf>
```

Then `$ pandoc code-test.md -o code-test.docx`, this results in a clean Word document like so (2nd line as block code):

```
Inline Code: <asdf>
Block code! <asdf>
```

Doing the same with PandocRuby results in a file like:

```
Inline Code: &lt;asdf&gt;
Block code! &lt;asdf&gt;
```

**Comment by alphabetum** [comment]
Thanks for the report, @jmuheim!

So far I've been unable to reproduce the behavior your are observing, where PandocRuby has different escaping on output from the Pandoc when using the `pandoc` command directly in the shell. In order to make this easier to observe directly, I added a new [test-output-equivalence](https://github.com/alphabetum/pandoc-ruby/tree/test-output-equivalence) branch with [some tests for both html and docx conversion](https://github.com/alphabetum/pandoc-ruby/blob/test-output-equivalence/test/test_output_equivalence.rb) and they pass on my local machine with Ruby 2.2.2p95. I also confirmed manually that the output in the docx files has the same escaping in both cases on my local machine.

If you could run the tests in that branch (you'll have to run `bundle install` again in that branch since there's another gem added for testing this) and see if they pass or not in your environment, that might help narrow down what the issue is. The only thing that immediately comes to mind is a locale issue (or I'm doing something wrong on my end. :smile: ).

Thanks!

**Comment by jmuheim** [comment]
I will check it out today, thanks for your efforts! Pandoc is such a cool thing, and having it easily available in Ruby is just great! :heart:

**Comment by jmuheim** [comment]
Interesting:

> 133 tests, 177 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
> 100% passed

I will have to dig into this further. Maybe some interplay between Rails and PandocRuby?

**Comment by jmuheim** [comment]
Just a shot in the dark: could it be because of not html safe strings in Rails?

**Comment by alphabetum** [comment]
That seems like it might be the case. It could be escaping the already-escaped brackets.

**Comment by jmuheim** [comment]
Okay, it seems it's not a problem of PandocRuby at all. I'm using `render_to_string(options)` in Rails, which does the HTML escape already, and pass this to Pandoc.

I have to find a way to render to string without HTML escaping.

Thanks for your help, though!

**Comment by jmuheim** [comment]
Added a StackOverflow question for this: http://stackoverflow.com/questions/31409636/rails-render-to-string-without-escaping-html-chars-i-e-and

**Comment by alphabetum** [comment]
Glad you found a solution. Thanks for the update!
