### ISSUE TITLE
Rails/PandocRuby: Exporting images results in “ERROR ThreadError: Attempt to unlock a mutex which is locked by another thread”

### ISSUE THREAD

**Issue by jmuheim** [alphabetum/pandoc-ruby#17]
I'm exporting some markdown using PandocRuby. Everything works great, except when I'm trying to add images that reside in the `public` folder, Rails freezes:

```
ERROR ThreadError: Attempt to unlock a mutex which is locked by another thread
/Users/josh/.rvm/gems/ruby-2.2.3@a4aa2/gems/rack-1.6.4/lib/rack/lock.rb:22:in `unlock'
/Users/josh/.rvm/gems/ruby-2.2.3@a4aa2/gems/rack-1.6.4/lib/rack/lock.rb:22:in `ensure in call'
/Users/josh/.rvm/gems/ruby-2.2.3@a4aa2/gems/rack-1.6.4/lib/rack/lock.rb:23:in `call'
/Users/josh/.rvm/gems/ruby-2.2.3@a4aa2/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/Users/josh/.rvm/gems/ruby-2.2.3@a4aa2/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/Users/josh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/josh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/josh/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

When I'm using images from some other place (and not from my local Ruby app), the export works as expected.

How can this problem be solved or circumvented?

Here's how I do the export to Pandoc:

```
# config/initializers/action_controller.rb
require 'rack/test'
require 'action_controller'

Mime::Type.register 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', :docx

ActionController::Renderers.add :docx do |filename, options|
  # Converting works great except < and > are escaped in codes!
  # http://stackoverflow.com/questions/30916575/converting-markdown-to-docx-using-pandoc-and-signs-in-code-is-translated-to
  # https://github.com/alphabetum/pandoc-ruby/issues/14
  document = PandocRuby.convert render_to_string(options), to: :docx
  send_data document, filename:    "#{filename}.docx",
                      type:        Mime::DOCX,
                      disposition: 'attachment'
end

module ActionController
  # For respond_with default
  class Responder
    def to_docx
      if @default_response
        @default_response.call(options)
      else
        controller.render({ docx: controller.action_name }.merge(options))
      end
    end
  end
end
```

And here's my view that renders a markdown string:

```
... a lot of code
![<%= finding.class.human_attribute_name :screenshot %>](<%= finding.screenshot.url %>)
... a lot of code
```

As already pointed out, using some other place to  get an image from works perfectly:

```
![<%= finding.class.human_attribute_name :screenshot %>](http://www.example.com/image.jpg)
```

**Comment by alphabetum** [comment]
It seems like this might be due to something related to Rails concurrency handling triggered by `<%= finding.screenshot.url %>`. Are the answers on the following stack overflow question applicable? 

http://stackoverflow.com/a/30228125

Based on my initial interpretation of the code here, it doesn't immediately appear to me that PandocRuby would be triggering the issue. The only place it's invoked is with `document = PandocRuby.convert render_to_string(options), to: :docx`, at which point the template, including the `<%= finding.screenshot.url %>` expression, would have already been rendered to a string.

If the above stack overflow question doesn't address or fix the issue, maybe another thing to check would be what `<%= finding.screenshot.url %>` renders to in the output of `render_to_string(options)` before it's passed to PandocRuby.
